
%% READ KINEMATICS FROM FILE (1) OR COMPUTE THEM (0)?

% KINEMATICS
read_kinematics = 0;
% ANIMATION ?
animation = 0;
% SAVE DATA?
save_data = 1;

%% AIRFOIL DISCRETIZATION
% NUMBER OF BOUNDARY POINTS (ODD NUMBER)
N_P = 100;

%% NUMERICAL PARAMETERS FOR PERIODIC PROBLEMS
% NUMBER OF SIMULATED PERIODS
NPs = 5;
% NUMBER OF TIME STEPS PER PERIOD
NTSPP = 100;
% NUMBER OF TIMESTEPS
NTS = NPs*NTSPP;
% MAX NUMBER OF ITERATIONS PER TIMESTEP
NITER = 100;
% MAX NUMBER OF VORTICES
NVs = 2*NTSPP;
% CONVERGENCE REPORT
reportConvergence = 5;

%% NUMERICAL PARAMETERS FOR OTHER PROBLEMS
% % NUMBER OF TIMESTEPS
% NTS = 1000;
% % TIMESTEP (seconds)
% dt = 0.1;
% % MAX NUMBER OF ITERATIONS PER TIMESTEP
% NITER = 100;
% % MAX NUMBER OF VORTICES
% NVs = 0.5*NTS;
% % CONVERGENCE REPORT
% reportConvergence = 5;