%% SIMULATION PARAMETERS
vis = 8.90e-4;
rho = 1000;
% AERODYNAMIC CHORD
chord = 1;
% ANGLE OF ATTACK
AoA = 0*pi/180;
% REYNOLDS NUMBER
Re = 1e4;
%Re = [1e4]';

% NONDIMENSIONAL AMPLITUDE
NonDimAmpl = 0.0;
%NonDimAmpl = [0.1 0.2 0.4]';
% REDUCED FREQUENCY
RedFreq = 1;
%RedFreq = [0.5:0.5:2]';
% PITCHING AMPLITUDE
PitchAmp = -0*pi/180;
%PitchAmp = -[0 10 20]'*pi/180;
% PHASE
phase = 0*pi/180;
% PIVOT (CHORD PERCENTAGE)
pivot = 0.3;
% ONLY LEADING EDGE?
onlyLE = 0; % 0 - STANDARD FLAPPING | 1 - LEADING-EDGE |
smoother = 117.7;
% ASYMMETRY OF KINEMATICS
zeta = 0.5;
% ANIMATION ?
animation = 0;

%% NUMERICAL PARAMETERS
% NUMBER OF SIMULATED PERIODS
NPs = 5;
% NUMBER OF TIME STEPS PER PERIOD
NTSPP = 100;
% NUMBER OF TIMESTEPS
NTS = NPs*NTSPP;
% MAX NUMBER OF ITERATIONS PER TIMESTEP
NITER = 100;
% MAX NUMBER OF VORTICES
NVs = 4*NTSPP;
% CONVERGENCE REPORT
reportConvergence = 5;

% NUMBER OF BOUNDARY POINTS (ODD NUMBER)
N_P = 100;
